#! /bin/sh

if [ "$DEBUG" = "True" ]; then
    uvicorn api_server:app --reload --host 0.0.0.0 --port 5000 --workers $WORKERS
else
    uvicorn api_server:app --host 0.0.0.0 --port 5000 --workers $WORKERS
fi

exec "$@"